apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyimg-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tinyimg
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tinyimg
    spec:
      containers:
        - name: myapp
          image: dunkbing/tinyimg:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 750m
              memory: 2048Mi
